/**
 * Image helpers.
 *
 * Source images live in /public/images/** and are pre-generated by the
 * optimisation step into two widths and two formats:
 *   name.jpg / name.webp                 (large, ~1800px)
 *   name-thumb.jpg / name-thumb.webp     (thumbnail, ~760px)
 *
 * `image-dimensions.json` records the intrinsic large-size dimensions so we
 * can always set width/height and avoid layout shift (good for Lighthouse/CLS).
 */
import dimensions from './image-dimensions.json';

type Dim = { w: number; h: number };
const dims = dimensions as Record<string, Dim>;

export type ResolvedImage = {
  /** Large JPEG (fallback) */
  src: string;
  webp: string;
  thumb: string;
  thumbWebp: string;
  width: number;
  height: number;
};

/** Resolve a /images/... .jpg path into all of its responsive variants. */
export function resolveImage(jpgPath: string): ResolvedImage {
  const base = jpgPath.replace(/\.jpg$/i, '');
  const dim = dims[jpgPath] ?? { w: 1600, h: 1067 };
  return {
    src: `${base}.jpg`,
    webp: `${base}.webp`,
    thumb: `${base}-thumb.jpg`,
    thumbWebp: `${base}-thumb.webp`,
    width: dim.w,
    height: dim.h,
  };
}

/** Absolute URL for Open Graph tags. */
export function absoluteUrl(path: string, siteUrl: string): string {
  return new URL(path, siteUrl).toString();
}
